#! /bin/bash

file=
if [ -f $1 ] ; then
   file=$1
fi

java -classpath ./build/libs/* io.dukecvar.monpoke.Play $file
#java -classpath ./out/artifacts/monpoke_main_jar/* io.dukecvar.monpoke.Play $file
